import React from 'react';
import Head from 'next/head';
import getConfig from 'next/config';

const { publicRuntimeConfig } = getConfig();

type Biodata = {
  id: number;
  name: string;
};

export default function Home() {
  const [biodatas, setBiodatas] = React.useState<Biodata[]>([]);

  React.useEffect(() => {
    fetch(publicRuntimeConfig.apiUrl)
      .then((res) => res.json())
      .then((res: Biodata[]) => setBiodatas(res));
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ol>
        {biodatas.map(({ id, name }) => (
          <li key={id}>{name}</li>
        ))}
      </ol>
    </div>
  );
}
